### ISSUE TITLE
can anyone confirm if this is working?

### ISSUE THREAD

**Issue by uptownhr** [alibaba-aero/nuxt-google-optimize#1]
I've attempted to use this module recently and all looked fine. However, after following the google dev guide for setting up the experiments. I could not get any session record tracked in the GO interface.

**Comment by uptownhr** [comment]
ok so i checked today and confirmed that sessions are now being tracked. I'm amazed that the reporting data is sooo delayed.

**Comment by farzadso** [comment]
Yes, Google Analytics data usually takes around 24 hours to show up

**Comment by brandonaaskov** [comment]
Just learned this ☝️ and am also surprised by that.
